AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  SpotFinOpsRoleArn:
    Value: !GetAtt 'SpotFinOpsRole.Arn'
Parameters:
  RoleName:
    Type: String
    Default: SpotByNetApp_Finops_FullPermission
  PolicyName:
    Type: String
    Default: SpotByNetApp_Finops_FullPermission_Policy
Resources:
  SpotFinOpsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref 'PolicyName'
      Description: Spot by NetApp Finops Full Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - es:ListElasticsearchInstanceTypes
              - es:DescribeReservedElasticsearchInstanceOfferings
              - es:DescribeReservedElasticsearchInstances
              - es:PurchaseReservedElasticsearchInstanceOffering
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicyElasticSearch
          - Action:
              - rds:DescribeReservedDBInstances
              - rds:DescribeDBInstances
              - rds:DescribeReservedDBInstancesOfferings
              - rds:PurchaseReservedDBInstancesOffering
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicyRDS
          - Action:
              - redshift:DescribeReservedNodeOfferings
              - redshift:DescribeReservedNodes
              - redshift:DescribeClusters
              - redshift:PurchaseReservedNodeOffering
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicyRedshift
          - Action:
              - elasticache:DescribeReservedCacheNodesOfferings
              - elasticache:DescribeReservedCacheNodes
              - elasticache:DescribeCacheClusters
              - elasticache:PurchaseReservedCacheNodesOffering
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicyElasticache
          - Action:
              - dynamodb:DescribeReservedCapacityOfferings
              - dynamodb:DescribeReservedCapacity
              - dynamodb:PurchaseReservedCapacityOfferings
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicyDynamoDB
          - Action:
              - ec2:Describe*
              - ec2:List*
              - ec2:GetHostReservationPurchasePreview
              - ec2:GetReservedInstancesExchangeQuote
              - ec2:ModifyReservedInstances
              - ec2:AcceptReservedInstancesExchangeQuote
              - ec2:CancelReservedInstancesListing
              - ec2:CreateReservedInstancesListing
              - ec2:PurchaseHostReservation
              - ec2:PurchaseReservedInstancesOffering
              - ec2:PurchaseScheduledInstances
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicyEC2
          - Action:
              - savingsplans:describe*
              - savingsplans:list*
              - savingsplans:CreateSavingsPlan
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicySavingsPlans
          - Action:
              - aws-portal:ViewBilling
              - aws-portal:ViewUsage
            Resource:
              - '*'
            Effect: Allow
            Sid: BillingdeprecatedJuly6
          - Action:
              - cur:DescribeReportDefinitions
              - cur:PutReportDefinition
              - cur:ModifyReportDefinition
              - ce:Get*
              - ce:Describe*
              - ce:List*
              - account:GetAccountInformation
              - billing:Get*
              - consolidatedbilling:Get*
              - consolidatedbilling:List*
              - invoicing:List*
              - invoicing:Get*
              - cur:Get*
              - cur:Validate*
              - freetier:Get*
              - organizations:List*
              - organizations:DescribeOrganization
              - servicequotas:List*
              - servicequotas:Get*
              - support:*
            Resource:
              - '*'
            Effect: Allow
            Sid: BillingPolicy
          - Sid: RequestServiceQuotaIncrease
            Effect: Allow
            Action: servicequotas:RequestServiceQuotaIncrease
            Resource:
              - arn:aws:servicequotas:*:*:rds/L-78E853F4
              - arn:aws:servicequotas:*:*:ec2/L-D0B7243C
              - arn:aws:servicequotas:*:*:redshift/L-58C8C0E8
          - Action:
              - iam:CreateServiceLinkedRole
              - iam:PutRolePolicy
            Resource: arn:aws:iam::*:role/aws-service-role/elasticache.amazonaws.com/AWSServiceRoleForElastiCache*
            Condition:
              StringLike:
                iam:AWSServiceName: elasticache.amazonaws.com
            Effect: Allow
            Sid: CreateServiceLinkedRole
  SpotFinOpsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Principal:
              AWS:
                - arn:aws:iam::884866656237:root
                - arn:aws:iam::627743545735:root
            Effect: Allow
      Description: Spot by NetApp FullPermissions Finops IAM Role
      ManagedPolicyArns:
        - !Ref 'SpotFinOpsManagedPolicy'
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      RoleName: !Ref 'RoleName'
