AWSTemplateFormatVersion: '2010-09-09'
Description: StackSet to link newly created AWS accounts to a Spot account
Parameters:
  Token:
    Description: The API Token for Spot.io
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+$
    NoEcho: true
Resources:
  SpotManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Spot.io Account Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: GeneralSpotInstancesAccess
            Action:
              - ec2:RequestSpotInstances
              - ec2:CancelSpotInstanceRequests
              - ec2:CreateSpotDatafeedSubscription
              - ec2:Describe*
              - ec2:AssociateAddress
              - ec2:AttachVolume
              - ec2:ConfirmProductInstance
              - ec2:CopyImage
              - ec2:CopySnapshot
              - ec2:CreateImage
              - ec2:CreateSnapshot
              - ec2:CreateTags
              - ec2:CreateVolume
              - ec2:DeleteTags
              - ec2:DisassociateAddress
              - ec2:ModifyImageAttribute
              - ec2:ModifyInstanceAttribute
              - ec2:MonitorInstances
              - ec2:RebootInstances
              - ec2:RegisterImage
              - ec2:RunInstances
              - ec2:StartInstances
              - ec2:StopInstances
              - ec2:TerminateInstances
              - ec2:UnassignPrivateIpAddresses
              - ec2:DeregisterImage
              - ec2:DeleteSnapshot
              - ec2:DeleteVolume
              - ec2:ModifyReservedInstances
              - ec2:CreateReservedInstancesListing
              - ec2:CancelReservedInstancesListing
              - ec2:ModifyNetworkInterfaceAttribute
              - ec2:DeleteNetworkInterface
              - iam:SimulatePrincipalPolicy
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessELB
            Action:
              - elasticloadbalancing:Describe*
              - elasticloadbalancing:Deregister*
              - elasticloadbalancing:Register*
              - elasticloadbalancing:RemoveTags
              - elasticloadbalancing:RegisterTargets
              - elasticloadbalancing:EnableAvailabilityZonesForLoadBalancer
              - elasticloadbalancing:DisableAvailabilityZonesForLoadBalancer
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessCloudWatch
            Action:
              - cloudwatch:DescribeAlarmHistory
              - cloudwatch:DescribeAlarms
              - cloudwatch:DescribeAlarmsForMetric
              - cloudwatch:GetMetricStatistics
              - cloudwatch:GetMetricData
              - cloudwatch:ListMetrics
              - cloudwatch:PutMetricData
              - cloudwatch:PutMetricAlarm
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessSNS
            Action:
              - sns:Publish
              - sns:ListTopics
              - sns:CreateTopic
              - sns:GetTopicAttributes
              - sns:ListSubscriptionsByTopic
              - sns:Subscribe
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessIAM
            Action:
              - iam:AddRoleToInstanceProfile
              - iam:ListInstanceProfiles
              - iam:ListInstanceProfilesForRole
              - iam:PassRole
              - iam:ListRoles
              - iam:ListAccountAliases
              - iam:GetPolicyVersion
              - iam:ListPolicies
              - iam:GetPolicy
              - iam:ListAttachedRolePolicies
              - organizations:ListAccounts
              - iam:CreateServiceLinkedRole
              - iam:PutRolePolicy
              - iam:GetInstanceProfile
              - iam:GetRolePolicy
              - iam:ListRolePolicies
            Effect: Allow
            Resource:
              - '*'
          - Sid: GeneralAccessElaticBeanstalk
            Action:
              - elasticbeanstalk:Describe*
              - elasticbeanstalk:RequestEnvironmentInfo
              - elasticbeanstalk:RetrieveEnvironmentInfo
              - elasticbeanstalk:ValidateConfigurationSettings
              - elasticbeanstalk:UpdateEnvironment
              - elasticbeanstalk:ListPlatformVersions
              - cloudformation:GetTemplate
              - cloudformation:DescribeStackResources
              - cloudformation:DescribeStackResource
              - cloudformation:DescribeStacks
              - cloudformation:ListStackResources
              - cloudformation:UpdateStack
              - cloudformation:DescribeStackEvents
              - logs:PutRetentionPolicy
              - logs:createLogGroup
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessAutoScalingGroups
            Action:
              - autoscaling:*
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessEks
            Action:
              - eks:ListClusters
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessEMR
            Action:
              - elasticmapreduce:*
              - s3:GetObject
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessECS
            Action:
              - ecs:List*
              - ecs:Describe*
              - ecs:DeregisterContainerInstance
              - ecs:UpdateContainerInstancesState
              - ecs:RegisterTaskDefinition
              - ecs:CreateService
              - application-autoscaling:PutScalingPolicy
              - application-autoscaling:RegisterScalableTarget
              - application-autoscaling:Describe*
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessBatch
            Action:
              - batch:List*
              - batch:Describe*
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessOpsWorks
            Action:
              - opsworks:DeregisterInstance
              - opsworks:DescribeInstances
              - opsworks:DescribeStacks
              - opsworks:DescribeLayers
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessCodeDeploy
            Action:
              - codedeploy:*
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessGeneralS3
            Action:
              - s3:GetObject
              - s3:List*
              - s3:GetBucketLocation
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccessRoute53
            Action:
              - route53:ListHostedZones
              - route53:ListResourceRecordSets
              - route53:ChangeResourceRecordSets
            Effect: Allow
            Resource:
              - '*'
          - Sid: AccesS3forElasticBeanstalk
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::elasticbeanstalk*
          - Sid: DockerBasedBeanstalkEnvironments
            Action:
              - ecs:Poll
              - ecs:DiscoverPollEndpoint
              - ecs:StartTelemetrySession
              - ecs:StartTask
              - ecs:StopTask
              - ecs:DescribeContainerInstances
              - ecs:RegisterContainerInstance
              - ecs:DeregisterContainerInstance
              - ecs:SubmitContainerStateChange
              - ecs:SubmitTaskStateChange
            Effect: Allow
            Resource:
              - '*'
          - Sid: SavingsPlan
            Action:
              - savingsplans:Describe*
              - savingsplans:List*
            Effect: Allow
            Resource:
              - '*'
          - Sid: Lambda
            Action:
              - lambda:ListFunctions
            Effect: Allow
            Resource:
              - '*'
  SpotAccount:
    Type: Custom::SpotAccount
    Properties:
      ServiceToken: !Sub
        - arn:aws:lambda:${Region}:178579023202:function:onboarding-stackset-account-lambda
        - Region: !Ref 'AWS::Region'
      AwsAccountId: !Ref 'AWS::AccountId'
      Token: !Ref 'Token'
    DependsOn:
      - 'SpotManagedPolicy'
  SpotExternalId:
    Type: Custom::SpotExternalId
    Properties:
      ServiceToken: !Sub
        - arn:aws:lambda:${Region}:178579023202:function:onboarding-stackset-external-id-lambda
        - Region: !Ref 'AWS::Region'
      SpotAccountId: !Ref 'SpotAccount'
      Token: !Ref 'Token'
    DependsOn:
     - "SpotAccount"
  SpotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::922761411349:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref 'SpotExternalId'
      ManagedPolicyArns:
        - !Ref 'SpotManagedPolicy'
    DependsOn:
      - "SpotAccount"
      - "SpotExternalId"
  SpotLinkedCredentials:
    Type: Custom::SpotLinkedCredentials
    Properties:
      ServiceToken: !Sub
        - arn:aws:lambda:${Region}:178579023202:function:spotinst-set-credentials
        - Region: !Ref 'AWS::Region'
      AccountId: !Ref 'SpotAccount'
      IamRoleArn: !GetAtt 'SpotRole.Arn'
      Token: !Ref 'Token'
      StackId: !Ref 'AWS::StackId'
      isTokenEncrypted: "false"
    DependsOn:
      - 'SpotAccount'
      - 'SpotExternalId'
      - 'SpotRole'
  RenamedSpotAccountByAlias:
    Type: Custom::RenamedSpotAccountByAlias
    Properties:
      ServiceToken: !Sub
        - arn:aws:lambda:${Region}:178579023202:function:onboarding-stackset-alias-lambda
        - Region: !Ref 'AWS::Region'
      SpotAccountId: !Ref 'SpotAccount'
      Token: !Ref 'Token'
      AwsAccountId: !Ref 'AWS::AccountId'
    DependsOn:
      - 'SpotAccount'
      - 'SpotLinkedCredentials'
Outputs:
  AccountId:
    Description: The Account ID for Spot.io
    Value: !Ref 'SpotAccount'
  ExternalId:
    Description: The External ID for Spot.io Role
    Value: !Ref 'SpotExternalId'
  SpotRoleArn:
    Description: The Account Role ARN used for Spot.io
    Value: !GetAtt 'SpotRole.Arn'
